workflows:
  testFlight:
    name: ELBOUNI
    integrations:
      app_store_connect: ELBOUNI
    environment:
      flutter: stable
      ios_signing:
        bundle_identifier: com.wadrop.app
        provisioning_profiles:
          - Provisioning_wadrop
        certificates:
          - certificate2
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - a.elbouni1996@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
